on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: windows build
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: ubuntu deps
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
                build-essential \
                curl \
                wget \
                libssl-dev \
                libgtk-3-dev \
                libappindicator3-dev \
                patchelf \
                librsvg2-dev
          fi
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: yarn
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: src-tauri
      - run: yarn --frozen-lockfile --ignore-scripts
      # hack: CI disabled to get around webpack warning: https://github.com/rustwasm/wasm-pack/issues/822
      # https://github.com/webpack/webpack/issues/8826
      # CI=false causes the build to not fail on warnings, fix this
      - run: CI=false yarn tauri build
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: yarn
      - run: yarn --frozen-lockfile --ignore-scripts
      - run: yarn test
