name: e2e

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: End to end tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Tauri deps
        run: |
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libgtksourceview-3.0-dev
          webkit2gtk-4.0
          libappindicator3-dev
          webkit2gtk-driver
          xvfb
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: src-tauri
      - name: Install tauri-driver
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: tauri-driver
      - run: yarn --frozen-lockfile --ignore-scripts
      - name: Build application
        run: yarn tauri build
      - name: Run tests
        run: xvfb-run yarn wdio
